### ISSUE TITLE
More Automation Required

### ISSUE THREAD

**Issue by MyNameIsBorat** [giuliodondi/kOS-ShuttleEntrySim#1]
Hi, 
the script is great as it is. but i think the whole point of using KOS is to minimise user inputs and setup. i think this has a great potential. looking forward to future improvements.

**Comment by MyNameIsBorat** [comment]
First thing i can suggest is calculation and execution of deorbit burn in consideration of mass and inclination.

**Comment by giuliodondi** [comment]
Of course it occurred to me that automating the search for the correct deorbit burn would be a good idea, but it's a much more difficult question than you may realise. During real mission planning they would employ advanced optimisaton agorithms to find the best solution, kOS is already struggling running this crude trajectory simulation so I'm not sure it'd be feasible.
The current setup is a glorified trial and error tool but way better than eyeballing the periapsis position.

Regarding automated node execution: kOS has a lot of trouble controlling the Shuttle in space with RCS because the steering controller is calibrated for engine gimbals. They have way more authority than RCS jets, especially in Realism Overhaul, and this leads to kOS freaking out and wasting way more RCS than necessary.
I've been working for ages to find a good solution for this without fugding with the individual PID gains but to no avail as of yet.

**Comment by MyNameIsBorat** [comment]
Thanks for clarifying. i think we dont need this much optimisation, we can do this with a simple function that takes certain parameters such as inclination, mass and orbit Ap and Pe. this can then spit out a distance for the shuttle to perform deorbit burn from. this won't be easy but a good enough working combo can be deduced and perfected from trial and error.

**Comment by MyNameIsBorat** [comment]
and regrading RCS, i think we can use RCS build aid mod to see which configuration balances the rcs best and then use this : https://ksp-kos.github.io/KOS/structures/misc/steeringmanager.html  to adjust the torque it calculates for correction.

**Comment by MyNameIsBorat** [comment]
take a look at this as well. https://www.youtube.com/watch?v=PhhRdpFlcdo

**Comment by giuliodondi** [comment]
First I'll work on implementing some preliminary architecture to handle different shuttle-like crafts (e.g. Shuttle Orbiter Construction Kit) and small fixes.

Afterwards I believe I can implement some entry interface profiles I found in a technical document. However I think the most I'll do is use these profiles to construct a preliminary deorbit node and still let the user adjust manually, so I don't need to handle extreme edge cases.
