### ISSUE TITLE
Srb for the Shuttle cant pull issue for Space-Shuttle-System-realistic-aerodynamics wont let me

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-ShuttleEntrySim#13]
for some reason theres a problem with the srb the solid fuel pban does not want to show up 
![Kerbal Space Program Screenshot 2024 01 01 - 00 48 54 97](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/3845f889-a397-40ae-a2dd-d24fd51299cd)

**Comment by giuliodondi** [comment]
This has nothing to do with the entry script, please, you need to open issues in the right repository, this is not a generic help desk place.

Also you need to be more detailed with your problem descriptions. What steps did you take, what mods did you install, in what order. If it used to work, what did you change since then. 
Try to imagine how I'm supposed to help you only with that picture
