### ISSUE TITLE
No Guidance window when running entry.ks

### ISSUE THREAD

**Issue by Nemo2507** [giuliodondi/kOS-ShuttleEntrySim#6]
Hello, i have a problem with the entry.ks, when i run entry.ks it doesn't show any errors in the kos window but the guidance window doesnt show up, can you help me?

**Comment by Nemo2507** [comment]
![image](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/143341029/f46d1097-7e15-4905-b855-19b907dd86bb)
what i meant by guidance window

**Comment by giuliodondi** [comment]
I'm afraid you're going to have to provide more infromation than that.
There can be so many reasons why the script can break. 

I need to know precisely what state your shuttle was in when you tried to run the script and how the configuration files are set up.
Also, the way you describe your problem it seems like the script just hangs or loops without doing anything before drawing the main gui, which should not be possible. I need a screenshot of exactly what command you executed and what the output was

**Comment by Nemo2507** [comment]
![image](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/143341029/23cd2f7c-0146-4fff-a6fd-581a7a2bc6f3)
heres my screen when i executed the command
My shuttle state is 45 degrees pitch forward RCS disabled thats all with 2 A.I.R.B.R.A.K.E.S

**Comment by giuliodondi** [comment]
The program looks like it's running ok to me. The fact that you have the hud gui is a good sign that the main gui should have been rendered by this point.

It looks to me that you're playing at a low screen resolution. This is important because when you create a kOS gui you also need to specify the x,y screen position of the origin. I believe the gui might simply be rendered off-screen.
Further evidece for this is that the hud gui looks gigantic.
What is your game resolution?

**Comment by Nemo2507** [comment]
1280x720
Update : I got it to appear now by increasing the resolution, but the space shuttle landing facility that you said included in the master Kos- shuttleentrysim folder is gone, i checked every folder in the main folder but I can’t seem to find it did you remove it?
Also how did you create Edwards AFB?

**Comment by giuliodondi** [comment]
Sorry for replying late. Glad the resolution fixed itself.

I forgot to update the README but the KerbalKonstruct defintions have been gone for a while.  
KK statics snap to the ground so, unless you have the exact same RSS terrain map that I have, the elevation and other stuff will be off. So it's pointless to include them since you have to measure the runway ane anyways.

For the moment for Edwards I use [STS locations by SpaceODY](https://forum.kerbalspaceprogram.com/topic/202701-1123-sts-locations-rss-v20/) and KerbalKonstructs statics.

**Comment by Nemo2507** [comment]
Ok one thing what runway did you intended to use when you make edwards afb bc it said runway 6/24 when i choose the edwards option but theres only 1 runway and it wasnt paved like in your video so just send me the map and circle the runway that you want edwards to use, and after you reply ill be closing the issue

**Comment by giuliodondi** [comment]
I think there is some misunderstanding here, let's clear it up.

First of all the STS locations mod was released about a year after I published the video,  it should have been obvious that in the video I wasn't using that mod for for Edwards. I recommended it because that's what I have right now.
In the video I placed a KK static and defined my runway on it, and that's the paved runway you see.  
In the SpaceODY mod there is no need to place a KK static because the terrain is solid (you can land anywhere in theory) and the "real" runway is clearly identifiable from the satellite texture. OF course you can still use KK to embellish the terrain with lights, statics and whatnot.

As far as the script config goes: there can never be just "one" runway, even if you have a single strip of tarmac you can land on it from two directions, and that makes it two distinct runways.  
The numbers are the compass heading of that runway end when you land on it, rounded and divided by 10 (e.g. if the heading is 63°, we call it runway 6). Of  course the two runway ends will have numbers that are 180° apart.

So "6" and "24" identify the two ends of the main paved runway at Edwards. The "Edwards" site config in my script is calibrated on the SpaceODY runway, or sat least the way it's placed in my KSP terrain.  
I expect the position to be pretty accurate for you, but the elevation might possibly be off depending on the RSS terrain map that you use, of course there is no way the script can account for that
