### ISSUE TITLE
Error occurs immediately after running the script

### ISSUE THREAD

**Issue by GlebKerman** [giuliodondi/kOS-ShuttleEntrySim#8]
When I run the entry.ks script, I get this peculiar error, I'm very new to kOS so I've got no idea what it means. Hopefully you can help, thanks in advance.
![unknown_2023 10 14-17 52](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/147939419/f2fe7ee0-0fce-4a66-9c4e-feaa790a7499)

**Comment by giuliodondi** [comment]
You forgot to add the two stock A.I.R.B.R.A.K.E.S.

By defualt the script is configured to use two of those to control speed and in you case it couldn't find any. 
If you want to use some custom airbrake part youll have to write code yo tell the script how to find and use it.

**Comment by GlebKerman** [comment]
Ah thank you (I forgot to add an airbrake to the right side of the orbiter), do they have to be scaled up with tweakscale? Or should I experiment with different sizes?

**Comment by giuliodondi** [comment]
if you're using the older SpaceODY Shuttle mod, use 150% scale. But in this case, you need to re-configure the Entry script since from your screenshot I can see you're using the default Shuttle_mono config intended for my fork of the Shuttle mod.

If instead you are already using my Shuttle fork, with the custom aerodynamics, leave them at 100% scale since the Shuttle is much draggier at subsonic speeds anyway.

In any case, I'm experimenting with getting the split rudder airbrake to work properly so this is all subject to change, hence why this is all not documented in the README.

**Comment by GlebKerman** [comment]
Ah understood, I'll keep them at 100% then, thanks for the help!
